### ISSUE TITLE
Cell indentation 

### ISSUE THREAD

**Issue by sergiocapozzi77** [catamphetamine/write-excel-file#4]
Hello, 

Is it possible to indent the content of a cell?

**Comment by catamphetamine** [comment]
Dunno

**Comment by SampsaKaskela** [comment]
@catamphetamine Would you be open to review the PR if I give this issue a go? Seems that it is just about adding `indent` attribute to `alignment` element so should be simple enough to implement.

**Comment by catamphetamine** [comment]
Hmm. You could try and tell me if it works and then maybe I’d add it, but no guarantee. For example, create a simple dummy spreadsheet without indent and then screenshot where in the unzipped xml code you add the attribute and how it looks visually (after re-zipping) in Excel before and after. Maybe then it would be more clear on what the feature is. No need to write code yet.

**Comment by SampsaKaskela** [comment]
So here is spreadsheet without indent
![withoutindent](https://github.com/user-attachments/assets/b758239c-bf95-4a7a-ae20-2d66f8ea4714)
Then with indent 2 added to first column to illustrate sort of children behavior.
![withindent](https://github.com/user-attachments/assets/48cc7fbc-e59c-410d-b1e5-b662eb3733d9)
In styles.xml it would be added like this
![xml](https://github.com/user-attachments/assets/236f8c63-8bc4-48ab-ad84-828ca0f54f1d)
I also made fork and used the textRotation implementation 7 months ago as baseline and it seemed to work when I ran the tests for one cell.
https://github.com/SampsaKaskela/write-excel-file

**Comment by catamphetamine** [comment]
@SampsaKaskela Ok. Following your screenshots, I added a new `indent: number` parameter to cell data in `write-excel-file@2.0.6`
